### ISSUE TITLE
How to implement it into a host web site?

### ISSUE THREAD

**Issue by Toronto899** [cdqa-suite/cdQA-ui#10]
I want to know the detail steps how to implement those whole cdQA into a hosting(like GCP or AWS) web site?  Many thanks!

**Comment by fmikaelian** [comment]
Hi @Toronto899 

`cdQA-ui` is a vue component so the easiest way to use it in a website is to build your website as a [vue app](https://vuejs.org/v2/guide/index.html) then import the `cdQA-ui` component (see import instructions: https://github.com/cdqa-suite/cdQA-ui#installation)

**Comment by morningstar899** [comment]
> Hi @Toronto899
> 
> `cdQA-ui` is a vue component so the easiest way to use it in a website is to build your website as a [vue app](https://vuejs.org/v2/guide/index.html) then import the `cdQA-ui` component (see import instructions: https://github.com/cdqa-suite/cdQA-ui#installation)

Hi,fmikaelian,  thank your reply !
