### ISSUE TITLE
After run "npm run serve", get  "x.x.x.x:8080 says Error: Network Error" --- Same error in the demo site

### ISSUE THREAD

**Issue by Toronto899** [cdqa-suite/cdQA-ui#11]
I run "npm run serve" and look like ui server up & running, after I select some example questions, like 'What is artificial intelligence?', and click search, then a small windows pop up ("x.x.x.x:8080 says Error: Network Error" -- same error in you guys demo site) and the search button just keep running without return any result, why?  Below are the detail logs after I run "npm run serve", FYI, thanks! 

xxxxx$ npm run serve
> cdqa-ui@1.0.8 serve /App/cdQA-ui
> vue serve ./load-dev-dependencies.js
There's a package.json in the current directory.
Did you mean npm run serve?
 INFO  Starting development server...
10% building 2/2 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /App/cdQA-ui/public
ℹ ｢wds｣: 404s will fallback to /index.html
98% after emitting
 WARNING  Compiled with 1 warnings                                                                       9:35:53 PM
Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'api_endpoint' is already defined (no-redeclare) at src/cdqaUI.vue:104:13:
  102 |         var api_endpoint = this.api_endpoint_gpu
  103 |       } else {
> 104 |         var api_endpoint = this.api_endpoint_cpu
      |             ^
  105 |       }
  106 |       let self = this;
  107 |       axios
1 error found.

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.150.0.2:8080/

**Comment by andrelmfarias** [comment]
Hi @Toronto899 ,

The demo on the site is not currently working because we shut down the server that was running the application a few weeks ago. We plan to launch the application on another server.

Regarding your case, I think it might be happening because you didn't launch the backend application and/or you did not connect the UI with the backend api.

For more information on how to do it, you can follow the steps presented in the **cdQA-ui** section in this [blogpost](https://towardsdatascience.com/how-to-create-your-own-question-answering-system-easily-with-python-2ef8abc8eb5).

**Comment by morningstar899** [comment]
> Hi @Toronto899 ,
> 
> The demo on the site is not currently working because we shut down the server that was running the application a few weeks ago. We plan to launch the application on another server.
> 
> Regarding your case, I think it might be happening because you didn't launch the backend REST API application and/or you did not connect the UI with the backend api.
> 
> For more information on how to do it, you can follow the steps presented in the **cdQA-ui** section in this [blogpost](https://towardsdatascience.com/how-to-create-your-own-question-answering-system-easily-with-python-2ef8abc8eb5).

Hi, Andre   Thank your reply first!   Yes, I have deploy a cdQA REST API "FLASK_APP=api.py flask run -h 0.0.0.0", but issue still happen when I run "npm run serve". The cdQA-ui is up, but still getting "Network Error". FYI.

**Comment by andrelmfarias** [comment]
Where is the REST API running? In your local machine or in a remote server on the cloud?

**Comment by morningstar899** [comment]
> Where is the REST API running? In your local machine or in a remote server on the cloud?

Hi, Andre      Both REST API & cdQA-ui server running at same machine (GCP VM), and I have open firewall for 8080 as well, so I can see the web site are up & running, but when I type in question and click search button, I got "Network Error" FYI, thanks!

**Comment by andrelmfarias** [comment]
@morningstar899 I just tested it by launching the cdqa REST API and the cdQA-ui on my machine and it works well:
![image](https://user-images.githubusercontent.com/43521764/65815566-63d85280-e1f1-11e9-91dd-2e2d63711340.png)

I am not sure why you are getting this "Network Error" but I think your UI server is not communicating with the cdqa REST API due to an incorrect port or IP address...

Have you tested the REST API by doing queries via HTTPie on the terminal? For instance you should get the following when doing a request via HTTPie:

![image](https://user-images.githubusercontent.com/43521764/65815624-35a74280-e1f2-11e9-8824-7ee9fc535ca6.png)

**Comment by andrelmfarias** [comment]
You should be sure that the address in the lines of code below is pointing to where the cdqa API is running:

https://github.com/cdqa-suite/cdQA-ui/blob/aaabe41cbec244216f39dc74de1bb43ec7e86b73/src/cdqaUI.vue#L71-L74

**Comment by morningstar899** [comment]
> @morningstar899 I just tested it by launching the cdqa REST API and the cdQA-ui on my machine and it works well:
> ![image](https://user-images.githubusercontent.com/43521764/65815566-63d85280-e1f1-11e9-91dd-2e2d63711340.png)
> 
> I am not sure why you are getting this "Network Error" but I think your UI server is not communicating with the cdqa REST API due to an incorrect port or IP address...
> 
> Have you tested the REST API by doing queries via HTTPie on the terminal? For instance you should get the following when doing a request via HTTPie:
> 
> ![image](https://user-images.githubusercontent.com/43521764/65815624-35a74280-e1f2-11e9-8824-7ee9fc535ca6.png)

Hi, Andre      My REST API is up & running, below is my test result: 
xiaodong_cai899@instance-1:~$ http localhost:5000/api query=='Who are the clients of BNP Paribas?' --timeout 60
HTTP/1.0 200 OK
Access-Control-Allow-Origin: *
Content-Length: 597
Content-Type: application/json
Date: Sat, 28 Sep 2019 13:26:08 GMT
Server: Werkzeug/0.16.0 Python/3.6.8

{
    "answer": "the heirs of our largest clients",
    "paragraph": "Over and above the « Next Generation Programme » training destined for the heirs of our largest clients, BNP Paribas Wealth Management developed a unique digital network, pioneer in its field. This international community, connected via a private application, permits the next generation users to develop their financial knowledge—all the while encouraging exchanges amongst the users themselves.",
    "query": "Who are the clients of BNP Paribas?",
    "title": "Private Banker International Awards 2015: 6 trophies for BNP Paribas"

**Comment by morningstar899** [comment]
> You also should be sure that the address in the lines of code below is pointing to where the cdqa API is running:
> 
> https://github.com/cdqa-suite/cdQA-ui/blob/aaabe41cbec244216f39dc74de1bb43ec7e86b73/src/cdqaUI.vue#L71-L74

Hi, Andre     Yes, I have same config. as you in "cdQA-ui/src/cdqaUI.vue".  But when start to run "npm run serve", I got this WARNING:
  _Compiled with 1 warnings                                                                       1:31:54 PM

Module Warning (from ./node_modules/eslint-loader/index.js):
error: 'api_endpoint' is already defined (no-redeclare) at src/cdqaUI.vue:104:13:
  102 |         var api_endpoint = this.api_endpoint_gpu
  103 |       } else {
> 104 |         var api_endpoint = this.api_endpoint_cpu
      |             ^
  105 |       }
  106 |       let self = this;
  107 |       axios_

**Comment by andrelmfarias** [comment]
I don't really know what the problem might be and how to solve it...

@fmikaelian do you have any ideas?

**Comment by n0thingLLM** [comment]
Hi @morningstar899 

The variable `api_endpoint` was declared 2 times. I've just pushed a fix. Can you retry to clone master branch and follow development instructions and tell us if it worked? https://github.com/cdqa-suite/cdQA-ui#development

**Comment by morningstar899** [comment]
> Can you retry to clone master branch

Hi, Felix    Thanks for the help, look like issue fixed.

**Comment by morningstar899** [comment]
> Hi @morningstar899
> 
> The variable `api_endpoint` was declared 2 times. I've just pushed a fix. Can you retry to clone master branch and follow development instructions and tell us if it worked? https://github.com/cdqa-suite/cdQA-ui#development

Hi, Felix    issue gone, thanks for the help!
